#!/usr/bin/env bash
# Configures local DNS resolution for localhost and facebook.com

# Write the modified content to a temporary file
sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > /tmp/hosts_temp

# Overwrite the original file with the new content
cat /tmp/hosts_temp > /etc/hosts

# Append the facebook.com rule
echo "8.8.8.8 facebook.com" >> /etc/hosts